export const entityConfigs = {
  drivers: {
    key: 'drivers',
    label: '驾驶员信息',
    basePath: '/api/drivers',
    idField: 'driverId',
    displayFields: ['driverId', 'name', 'idCardNumber', 'contactNumber', 'driverLicenseNumber', 'licenseType', 'currentPoints', 'status'],
    editableFields: ['name', 'idCardNumber', 'gender', 'birthdate', 'contactNumber', 'email', 'address', 'driverLicenseNumber', 'licenseType', 'allowedVehicleType', 'firstLicenseDate', 'issueDate', 'expiryDate', 'issuingAuthority', 'status', 'remarks'],
    fields: [
      { name: 'driverId', type: 'int', readOnly: true },
      { name: 'name', type: 'String' },
      { name: 'idCardNumber', type: 'String' },
      { name: 'gender', type: 'String' },
      { name: 'birthdate', type: 'DateTime' },
      { name: 'contactNumber', type: 'String' },
      { name: 'email', type: 'String' },
      { name: 'address', type: 'String' },
      { name: 'driverLicenseNumber', type: 'String' },
      { name: 'licenseType', type: 'String' },
      { name: 'allowedVehicleType', type: 'String' },
      { name: 'firstLicenseDate', type: 'DateTime' },
      { name: 'issueDate', type: 'DateTime' },
      { name: 'expiryDate', type: 'DateTime' },
      { name: 'issuingAuthority', type: 'String' },
      { name: 'currentPoints', type: 'int' },
      { name: 'totalDeductedPoints', type: 'int' },
      { name: 'status', type: 'String' },
      { name: 'createdAt', type: 'DateTime', readOnly: true },
      { name: 'updatedAt', type: 'DateTime', readOnly: true },
      { name: 'createdBy', type: 'String' },
      { name: 'updatedBy', type: 'String' },
      { name: 'deletedAt', type: 'DateTime' },
      { name: 'remarks', type: 'String' },
    ],
  },
  vehicles: {
    key: 'vehicles',
    label: '车辆信息',
    basePath: '/api/vehicles',
    idField: 'vehicleId',
    displayFields: ['vehicleId', 'licensePlate', 'vehicleType', 'brand', 'model', 'ownerName', 'ownerContact', 'status'],
    editableFields: ['licensePlate', 'plateColor', 'vehicleType', 'brand', 'model', 'vehicleColor', 'engineNumber', 'frameNumber', 'ownerName', 'ownerIdCard', 'ownerContact', 'ownerAddress', 'firstRegistrationDate', 'registrationDate', 'issuingAuthority', 'status', 'inspectionExpiryDate', 'insuranceExpiryDate', 'remarks'],
    fields: [
      { name: 'vehicleId', type: 'int', readOnly: true },
      { name: 'licensePlate', type: 'String' },
      { name: 'plateColor', type: 'String' },
      { name: 'vehicleType', type: 'String' },
      { name: 'brand', type: 'String' },
      { name: 'model', type: 'String' },
      { name: 'vehicleColor', type: 'String' },
      { name: 'engineNumber', type: 'String' },
      { name: 'frameNumber', type: 'String' },
      { name: 'ownerName', type: 'String' },
      { name: 'ownerIdCard', type: 'String' },
      { name: 'ownerContact', type: 'String' },
      { name: 'ownerAddress', type: 'String' },
      { name: 'firstRegistrationDate', type: 'DateTime' },
      { name: 'registrationDate', type: 'DateTime' },
      { name: 'issuingAuthority', type: 'String' },
      { name: 'status', type: 'String' },
      { name: 'inspectionExpiryDate', type: 'DateTime' },
      { name: 'insuranceExpiryDate', type: 'DateTime' },
      { name: 'createdAt', type: 'DateTime', readOnly: true },
      { name: 'updatedAt', type: 'DateTime', readOnly: true },
      { name: 'createdBy', type: 'String' },
      { name: 'updatedBy', type: 'String' },
      { name: 'deletedAt', type: 'DateTime' },
      { name: 'remarks', type: 'String' },
      { name: 'plateStatusSnapshot', type: 'String' },
    ],
  },
  offenses: {
    key: 'offenses',
    label: '违法记录',
    basePath: '/api/offenses',
    idField: 'offenseId',
    displayFields: ['offenseId', 'offenseNumber', 'offenseTime', 'offenseLocation', 'driverName', 'licensePlate', 'offenseType', 'fineAmount', 'deductedPoints', 'processStatus'],
    editableFields: ['offenseCode', 'offenseNumber', 'offenseTime', 'offenseLocation', 'offenseProvince', 'offenseCity', 'driverId', 'vehicleId', 'offenseDescription', 'evidenceType', 'evidenceUrls', 'enforcementAgency', 'fineAmount', 'deductedPoints', 'detentionDays', 'remarks'],
    fields: [
      { name: 'offenseId', type: 'int', readOnly: true },
      { name: 'offenseCode', type: 'String' },
      { name: 'offenseNumber', type: 'String' },
      { name: 'offenseTime', type: 'DateTime' },
      { name: 'offenseLocation', type: 'String' },
      { name: 'offenseProvince', type: 'String' },
      { name: 'offenseCity', type: 'String' },
      { name: 'driverId', type: 'int' },
      { name: 'vehicleId', type: 'int' },
      { name: 'offenseDescription', type: 'String' },
      { name: 'evidenceType', type: 'String' },
      { name: 'evidenceUrls', type: 'String' },
      { name: 'enforcementAgency', type: 'String' },
      { name: 'enforcementOfficer', type: 'String' },
      { name: 'enforcementDevice', type: 'String' },
      { name: 'processStatus', type: 'String' },
      { name: 'notificationStatus', type: 'String' },
      { name: 'notificationTime', type: 'DateTime' },
      { name: 'fineAmount', type: 'double' },
      { name: 'deductedPoints', type: 'int' },
      { name: 'detentionDays', type: 'int' },
      { name: 'processTime', type: 'DateTime' },
      { name: 'processHandler', type: 'String' },
      { name: 'processResult', type: 'String' },
      { name: 'createdAt', type: 'DateTime', readOnly: true },
      { name: 'updatedAt', type: 'DateTime', readOnly: true },
      { name: 'createdBy', type: 'String' },
      { name: 'updatedBy', type: 'String' },
      { name: 'deletedAt', type: 'DateTime' },
      { name: 'remarks', type: 'String' },
      { name: 'licensePlate', type: 'String' },
      { name: 'driverName', type: 'String' },
      { name: 'offenseType', type: 'String' },
    ],
  },
  deductions: {
    key: 'deductions',
    label: '扣分记录',
    basePath: '/api/deductions',
    idField: 'deductionId',
    displayFields: ['deductionId', 'offenseId', 'driverId', 'deductedPoints', 'deductionTime', 'scoringCycle', 'status', 'handler'],
    editableFields: ['offenseId', 'driverId', 'deductedPoints', 'deductionTime', 'scoringCycle', 'status', 'restoreReason', 'remarks'],
    fields: [
      { name: 'deductionId', type: 'int', readOnly: true },
      { name: 'offenseId', type: 'int' },
      { name: 'driverId', type: 'int' },
      { name: 'deductedPoints', type: 'int' },
      { name: 'deductionTime', type: 'DateTime' },
      { name: 'scoringCycle', type: 'String' },
      { name: 'handler', type: 'String' },
      { name: 'handlerDept', type: 'String' },
      { name: 'approver', type: 'String' },
      { name: 'approvalTime', type: 'DateTime' },
      { name: 'status', type: 'String' },
      { name: 'restoreTime', type: 'DateTime' },
      { name: 'restoreReason', type: 'String' },
      { name: 'createdAt', type: 'DateTime', readOnly: true },
      { name: 'updatedAt', type: 'DateTime', readOnly: true },
      { name: 'remarks', type: 'String' },
    ],
  },
  fines: {
    key: 'fines',
    label: '罚款记录',
    basePath: '/api/fines',
    idField: 'fineId',
    displayFields: ['fineId', 'offenseId', 'fineNumber', 'fineAmount', 'lateFee', 'totalAmount', 'paymentDeadline', 'paymentStatus', 'status'],
    editableFields: ['offenseId', 'fineNumber', 'fineAmount', 'lateFee', 'totalAmount', 'fineDate', 'paymentDeadline', 'issuingAuthority', 'paymentStatus', 'status', 'remarks'],
    fields: [
      { name: 'fineId', type: 'int', readOnly: true },
      { name: 'offenseId', type: 'int' },
      { name: 'fineNumber', type: 'String' },
      { name: 'fineAmount', type: 'double' },
      { name: 'lateFee', type: 'double' },
      { name: 'totalAmount', type: 'double' },
      { name: 'fineDate', type: 'DateTime' },
      { name: 'paymentDeadline', type: 'DateTime' },
      { name: 'issuingAuthority', type: 'String' },
      { name: 'handler', type: 'String' },
      { name: 'approver', type: 'String' },
      { name: 'paymentStatus', type: 'String' },
      { name: 'paidAmount', type: 'double' },
      { name: 'unpaidAmount', type: 'double' },
      { name: 'fineTime', type: 'String' },
      { name: 'payee', type: 'String' },
      { name: 'accountNumber', type: 'String' },
      { name: 'bank', type: 'String' },
      { name: 'receiptNumber', type: 'String' },
      { name: 'createdAt', type: 'DateTime', readOnly: true },
      { name: 'updatedAt', type: 'DateTime', readOnly: true },
      { name: 'createdBy', type: 'String' },
      { name: 'updatedBy', type: 'String' },
      { name: 'deletedAt', type: 'DateTime' },
      { name: 'remarks', type: 'String' },
      { name: 'status', type: 'String' },
    ],
  },
  payments: {
    key: 'payments',
    label: '缴费记录',
    basePath: '/api/payments',
    idField: 'paymentId',
    useCustomPage: true,
    displayFields: ['paymentId', 'fineId', 'paymentNumber', 'paymentAmount', 'paymentMethod', 'paymentTime', 'payerName', 'paymentStatus', 'receiptNumber'],
    editableFields: ['fineId', 'paymentAmount', 'paymentMethod', 'paymentChannel', 'payerName', 'payerContact', 'remarks'],
    fields: [
      { name: 'paymentId', type: 'int', readOnly: true },
      { name: 'fineId', type: 'int' },
      { name: 'paymentNumber', type: 'String' },
      { name: 'paymentAmount', type: 'double' },
      { name: 'paymentMethod', type: 'String' },
      { name: 'paymentTime', type: 'DateTime' },
      { name: 'paymentChannel', type: 'String' },
      { name: 'payerName', type: 'String' },
      { name: 'payerIdCard', type: 'String' },
      { name: 'payerContact', type: 'String' },
      { name: 'bankName', type: 'String' },
      { name: 'bankAccount', type: 'String' },
      { name: 'transactionId', type: 'String' },
      { name: 'receiptNumber', type: 'String' },
      { name: 'receiptUrl', type: 'String' },
      { name: 'paymentStatus', type: 'String' },
      { name: 'refundAmount', type: 'double' },
      { name: 'refundTime', type: 'DateTime' },
      { name: 'createdAt', type: 'DateTime', readOnly: true },
      { name: 'updatedAt', type: 'DateTime', readOnly: true },
      { name: 'createdBy', type: 'String' },
      { name: 'updatedBy', type: 'String' },
      { name: 'deletedAt', type: 'DateTime' },
      { name: 'remarks', type: 'String' },
    ],
  },
  offenseTypes: {
    key: 'offenseTypes',
    label: '违法类型字典',
    basePath: '/api/offense-types',
    idField: 'typeId',
    displayFields: ['typeId', 'offenseCode', 'offenseName', 'category', 'standardFineAmount', 'deductedPoints', 'severityLevel', 'status'],
    editableFields: ['offenseCode', 'offenseName', 'category', 'description', 'standardFineAmount', 'minFineAmount', 'maxFineAmount', 'deductedPoints', 'detentionDays', 'licenseSuspensionDays', 'severityLevel', 'legalBasis', 'status', 'remarks'],
    fields: [
      { name: 'typeId', type: 'int', readOnly: true },
      { name: 'offenseCode', type: 'String' },
      { name: 'offenseName', type: 'String' },
      { name: 'category', type: 'String' },
      { name: 'description', type: 'String' },
      { name: 'standardFineAmount', type: 'double' },
      { name: 'minFineAmount', type: 'double' },
      { name: 'maxFineAmount', type: 'double' },
      { name: 'deductedPoints', type: 'int' },
      { name: 'detentionDays', type: 'int' },
      { name: 'licenseSuspensionDays', type: 'int' },
      { name: 'severityLevel', type: 'String' },
      { name: 'legalBasis', type: 'String' },
      { name: 'status', type: 'String' },
      { name: 'createdAt', type: 'DateTime', readOnly: true },
      { name: 'updatedAt', type: 'DateTime', readOnly: true },
      { name: 'deletedAt', type: 'DateTime' },
      { name: 'remarks', type: 'String' },
    ],
  },
  appeals: {
    key: 'appeals',
    label: '申诉记录',
    basePath: '/api/appeals',
    idField: 'appealId',
    displayFields: ['appealId', 'appealNumber', 'appellantName', 'appealType', 'appealTime', 'acceptanceStatus', 'processStatus', 'processResult'],
    editableFields: ['offenseId', 'appealNumber', 'appellantName', 'appellantIdCard', 'appellantContact', 'appellantEmail', 'appellantAddress', 'appealType', 'appealReason', 'appealTime', 'evidenceDescription', 'evidenceUrls'],
    fields: [
      { name: 'appealId', type: 'int', readOnly: true },
      { name: 'offenseId', type: 'int' },
      { name: 'appealNumber', type: 'String' },
      { name: 'appellantName', type: 'String' },
      { name: 'appellantIdCard', type: 'String' },
      { name: 'appellantContact', type: 'String' },
      { name: 'appellantEmail', type: 'String' },
      { name: 'appellantAddress', type: 'String' },
      { name: 'appealType', type: 'String' },
      { name: 'appealReason', type: 'String' },
      { name: 'appealTime', type: 'DateTime' },
      { name: 'evidenceDescription', type: 'String' },
      { name: 'evidenceUrls', type: 'String' },
      { name: 'acceptanceStatus', type: 'String' },
      { name: 'acceptanceTime', type: 'DateTime' },
      { name: 'acceptanceHandler', type: 'String' },
      { name: 'rejectionReason', type: 'String' },
      { name: 'processStatus', type: 'String' },
      { name: 'processTime', type: 'DateTime' },
      { name: 'processResult', type: 'String' },
      { name: 'processHandler', type: 'String' },
      { name: 'createdAt', type: 'DateTime', readOnly: true },
      { name: 'updatedAt', type: 'DateTime', readOnly: true },
    ],
  },
  progress: {
    key: 'progress',
    label: '业务进度',
    basePath: '/api/progress',
    idField: 'id',
    useCustomPage: true,
    displayFields: ['id', 'businessType', 'businessId', 'businessStatus', 'userId', 'createdTime', 'modifiedTime'],
    editableFields: [],
    fields: [
      { name: 'id', type: 'int', readOnly: true },
      { name: 'idempotencyKey', type: 'String' },
      { name: 'requestMethod', type: 'String' },
      { name: 'requestUrl', type: 'String' },
      { name: 'requestParams', type: 'String' },
      { name: 'businessType', type: 'String' },
      { name: 'businessId', type: 'int' },
      { name: 'businessStatus', type: 'String' },
      { name: 'userId', type: 'int' },
      { name: 'requestIp', type: 'String' },
      { name: 'createdTime', type: 'DateTime', readOnly: true },
      { name: 'modifiedTime', type: 'DateTime', readOnly: true },
      { name: 'deletedAt', type: 'DateTime' },
    ],
  },
  users: {
    key: 'users',
    label: '用户管理',
    basePath: '/api/users',
    idField: 'userId',
    useCustomPage: true,
    displayFields: ['userId', 'username', 'realName', 'contactNumber', 'email', 'department', 'position', 'status', 'lastLoginTime'],
    editableFields: ['username', 'realName', 'gender', 'contactNumber', 'email', 'department', 'position', 'employeeNumber', 'status', 'accountExpiryDate', 'remarks'],
    fields: [
      { name: 'userId', type: 'int', readOnly: true },
      { name: 'username', type: 'String' },
      { name: 'password', type: 'String' },
      { name: 'salt', type: 'String' },
      { name: 'realName', type: 'String' },
      { name: 'idCardNumber', type: 'String' },
      { name: 'gender', type: 'String' },
      { name: 'contactNumber', type: 'String' },
      { name: 'email', type: 'String' },
      { name: 'department', type: 'String' },
      { name: 'position', type: 'String' },
      { name: 'employeeNumber', type: 'String' },
      { name: 'status', type: 'String' },
      { name: 'accountExpiryDate', type: 'DateTime' },
      { name: 'loginFailures', type: 'int' },
      { name: 'lastLoginTime', type: 'DateTime' },
      { name: 'lastLoginIp', type: 'String' },
      { name: 'passwordUpdateTime', type: 'DateTime' },
      { name: 'createdTime', type: 'DateTime', readOnly: true },
      { name: 'modifiedTime', type: 'DateTime', readOnly: true },
      { name: 'createdBy', type: 'String' },
      { name: 'updatedBy', type: 'String' },
      { name: 'deletedAt', type: 'DateTime' },
      { name: 'remarks', type: 'String' },
    ],
  },
  roles: {
    key: 'roles',
    label: '角色管理',
    basePath: '/api/roles',
    idField: 'roleId',
    displayFields: ['roleId', 'roleCode', 'roleName', 'roleType', 'dataScope', 'status', 'sortOrder'],
    editableFields: ['roleCode', 'roleName', 'roleType', 'roleDescription', 'dataScope', 'status', 'sortOrder', 'remarks'],
    fields: [
      { name: 'roleId', type: 'int', readOnly: true },
      { name: 'roleCode', type: 'String' },
      { name: 'roleName', type: 'String' },
      { name: 'roleType', type: 'String' },
      { name: 'roleDescription', type: 'String' },
      { name: 'dataScope', type: 'String' },
      { name: 'status', type: 'String' },
      { name: 'sortOrder', type: 'int' },
      { name: 'createdTime', type: 'DateTime', readOnly: true },
      { name: 'modifiedTime', type: 'DateTime', readOnly: true },
      { name: 'createdBy', type: 'String' },
      { name: 'updatedBy', type: 'String' },
      { name: 'deletedAt', type: 'DateTime' },
      { name: 'remarks', type: 'String' },
    ],
  },
  permissions: {
    key: 'permissions',
    label: '权限管理',
    basePath: '/api/permissions',
    idField: 'permissionId',
    displayFields: ['permissionId', 'permissionCode', 'permissionName', 'permissionType', 'menuPath', 'isVisible', 'status', 'sortOrder'],
    editableFields: ['parentId', 'permissionCode', 'permissionName', 'permissionType', 'permissionDescription', 'menuPath', 'menuIcon', 'component', 'isVisible', 'isExternal', 'sortOrder', 'status', 'remarks'],
    fields: [
      { name: 'permissionId', type: 'int', readOnly: true },
      { name: 'parentId', type: 'int' },
      { name: 'permissionCode', type: 'String' },
      { name: 'permissionName', type: 'String' },
      { name: 'permissionType', type: 'String' },
      { name: 'permissionDescription', type: 'String' },
      { name: 'menuPath', type: 'String' },
      { name: 'menuIcon', type: 'String' },
      { name: 'component', type: 'String' },
      { name: 'apiPath', type: 'String' },
      { name: 'apiMethod', type: 'String' },
      { name: 'isVisible', type: 'bool' },
      { name: 'isExternal', type: 'bool' },
      { name: 'sortOrder', type: 'int' },
      { name: 'status', type: 'String' },
      { name: 'createdTime', type: 'DateTime', readOnly: true },
      { name: 'modifiedTime', type: 'DateTime', readOnly: true },
      { name: 'createdBy', type: 'String' },
      { name: 'updatedBy', type: 'String' },
      { name: 'deletedAt', type: 'DateTime' },
      { name: 'remarks', type: 'String' },
    ],
  },
  systemSettings: {
    key: 'systemSettings',
    label: '系统设置',
    basePath: '/api/system/settings',
    idField: 'settingId',
    displayFields: ['settingId', 'systemName', 'systemVersion', 'systemDescription', 'dateFormat', 'pageSize', 'loginTimeout', 'sessionTimeout', 'modifiedTime'],
    editableFields: ['systemName', 'systemDescription', 'copyrightInfo', 'loginTimeout', 'sessionTimeout', 'dateFormat', 'pageSize', 'remarks'],
    fields: [
      { name: 'settingId', type: 'int', readOnly: true },
      { name: 'settingKey', type: 'String' },
      { name: 'settingValue', type: 'String' },
      { name: 'settingType', type: 'String' },
      { name: 'category', type: 'String' },
      { name: 'description', type: 'String' },
      { name: 'isEncrypted', type: 'bool' },
      { name: 'isEditable', type: 'bool' },
      { name: 'sortOrder', type: 'int' },
      { name: 'createdTime', type: 'DateTime', readOnly: true },
      { name: 'modifiedTime', type: 'DateTime', readOnly: true },
      { name: 'updatedBy', type: 'String' },
      { name: 'deletedAt', type: 'DateTime' },
      { name: 'remarks', type: 'String' },
      { name: 'systemName', type: 'String' },
      { name: 'systemVersion', type: 'String' },
      { name: 'systemDescription', type: 'String' },
      { name: 'copyrightInfo', type: 'String' },
      { name: 'storagePath', type: 'String' },
      { name: 'loginTimeout', type: 'int' },
      { name: 'sessionTimeout', type: 'int' },
      { name: 'dateFormat', type: 'String' },
      { name: 'pageSize', type: 'int' },
      { name: 'smtpServer', type: 'String' },
      { name: 'emailAccount', type: 'String' },
      { name: 'emailPassword', type: 'String' },
    ],
  },
  backups: {
    key: 'backups',
    label: '备份记录',
    basePath: '/api/system/backup',
    idField: 'backupId',
    displayFields: ['backupId', 'backupType', 'backupFileName', 'backupFileSize', 'backupTime', 'backupDuration', 'backupHandler', 'restoreStatus', 'status'],
    editableFields: [],
    fields: [
      { name: 'backupId', type: 'int', readOnly: true },
      { name: 'backupType', type: 'String' },
      { name: 'backupFileName', type: 'String' },
      { name: 'backupFilePath', type: 'String' },
      { name: 'backupFileSize', type: 'int' },
      { name: 'backupTime', type: 'DateTime' },
      { name: 'backupDuration', type: 'int' },
      { name: 'backupHandler', type: 'String' },
      { name: 'restoreTime', type: 'DateTime' },
      { name: 'restoreDuration', type: 'int' },
      { name: 'restoreStatus', type: 'String' },
      { name: 'restoreHandler', type: 'String' },
      { name: 'errorMessage', type: 'String' },
      { name: 'status', type: 'String' },
      { name: 'createdTime', type: 'DateTime', readOnly: true },
      { name: 'modifiedTime', type: 'DateTime', readOnly: true },
      { name: 'deletedAt', type: 'DateTime' },
      { name: 'remarks', type: 'String' },
    ],
  },
  loginLogs: {
    key: 'loginLogs',
    label: '登录日志',
    basePath: '/api/logs/login',
    idField: 'logId',
    displayFields: ['logId', 'username', 'loginTime', 'logoutTime', 'loginResult', 'failureReason', 'loginIp', 'loginLocation', 'browserType', 'osType', 'deviceType'],
    editableFields: [],
    fields: [
      { name: 'logId', type: 'int', readOnly: true },
      { name: 'username', type: 'String' },
      { name: 'loginTime', type: 'DateTime' },
      { name: 'logoutTime', type: 'DateTime' },
      { name: 'loginResult', type: 'String' },
      { name: 'failureReason', type: 'String' },
      { name: 'loginIp', type: 'String' },
      { name: 'loginLocation', type: 'String' },
      { name: 'browserType', type: 'String' },
      { name: 'browserVersion', type: 'String' },
      { name: 'osType', type: 'String' },
      { name: 'osVersion', type: 'String' },
      { name: 'deviceType', type: 'String' },
      { name: 'userAgent', type: 'String' },
      { name: 'sessionId', type: 'String' },
      { name: 'token', type: 'String' },
      { name: 'createdAt', type: 'DateTime', readOnly: true },
      { name: 'deletedAt', type: 'DateTime' },
      { name: 'remarks', type: 'String' },
    ],
  },
  operationLogs: {
    key: 'operationLogs',
    label: '操作日志',
    basePath: '/api/logs/operation',
    idField: 'logId',
    displayFields: ['logId', 'operationType', 'operationModule', 'operationFunction', 'operationContent', 'operationTime', 'username', 'requestMethod', 'requestUrl', 'requestIp', 'operationResult', 'errorMessage', 'executionTime'],
    editableFields: [],
    fields: [
      { name: 'logId', type: 'int', readOnly: true },
      { name: 'operationType', type: 'String' },
      { name: 'operationModule', type: 'String' },
      { name: 'operationFunction', type: 'String' },
      { name: 'operationContent', type: 'String' },
      { name: 'operationTime', type: 'DateTime' },
      { name: 'userId', type: 'int' },
      { name: 'username', type: 'String' },
      { name: 'realName', type: 'String' },
      { name: 'requestMethod', type: 'String' },
      { name: 'requestUrl', type: 'String' },
      { name: 'requestParams', type: 'String' },
      { name: 'requestIp', type: 'String' },
      { name: 'operationResult', type: 'String' },
      { name: 'responseData', type: 'String' },
      { name: 'errorMessage', type: 'String' },
      { name: 'executionTime', type: 'int' },
      { name: 'oldValue', type: 'String' },
      { name: 'newValue', type: 'String' },
      { name: 'createdAt', type: 'DateTime', readOnly: true },
      { name: 'deletedAt', type: 'DateTime' },
      { name: 'remarks', type: 'String' },
    ],
  },
  systemLogs: {
    key: 'systemLogs',
    label: '系统日志',
    basePath: '/api/system/logs',
    idField: 'id',
    useCustomPage: true,
    displayFields: ['logId', 'logType', 'logContent', 'operationTime', 'operationUser', 'operationIpAddress', 'remarks'],
    editableFields: [],
    fields: [
      { name: 'logId', type: 'int', readOnly: true },
      { name: 'logType', type: 'String', readOnly: true },
      { name: 'logContent', type: 'String', readOnly: true },
      { name: 'operationTime', type: 'DateTime', readOnly: true },
      { name: 'operationUser', type: 'String', readOnly: true },
      { name: 'operationIpAddress', type: 'String', readOnly: true },
      { name: 'remarks', type: 'String', readOnly: true },
    ],
  },
};

export const entityList = Object.values(entityConfigs);
