import {
  FiHome,
  FiUsers,
  FiShield,
  FiAlertTriangle,
  FiTruck,
  FiCreditCard,
  FiFileText,
  FiSettings,
  FiActivity,
  FiClipboard,
  FiMap,
  FiMessageCircle,
  FiLayers,
  FiBookOpen,
  FiTool,
  FiLogOut,
} from 'react-icons/fi';

export const managerNav = [
  { label: '管理仪表盘', path: '/dashboard', icon: FiHome },
  { label: '交通违法概览', path: '/trafficViolationScreen', icon: FiActivity },
  { label: '违法记录', path: '/offenseList', icon: FiAlertTriangle },
  { label: '违法类型', path: '/offenseType', icon: FiShield },
  { label: '扣分记录', path: '/deductionManagement', icon: FiClipboard },
  { label: '罚款记录', path: '/fineList', icon: FiCreditCard },
  { label: '缴费记录', path: '/paymentRecord', icon: FiCreditCard },
  { label: '申诉管理', path: '/appealManagement', icon: FiFileText },
  { label: '驾驶员管理', path: '/driverList', icon: FiUsers },
  { label: '车辆管理', path: '/vehicleList', icon: FiTruck },
  { label: '业务进度', path: '/progressManagement', icon: FiLayers },
  { label: '用户管理', path: '/userManagementPage', icon: FiUsers },
  { label: '权限管理', path: '/permissionManagement', icon: FiShield },
  { label: '角色管理', path: '/roleManagement', icon: FiShield },
  { label: '日志管理', path: '/logManagement', icon: FiClipboard },
  { label: '系统设置', path: '/systemSettings', icon: FiSettings },
  { label: '备份与恢复', path: '/backupAndRestore', icon: FiTool },
  { label: 'AI 助手', path: '/aiChat', icon: FiMessageCircle },
  { label: '数据地图', path: '/map', icon: FiMap },
  { label: '管理员信息', path: '/managerPersonalPage', icon: FiBookOpen },
  { label: '管理员设置', path: '/managerSetting', icon: FiSettings },
];

export const userNav = [
  { label: '用户仪表盘', path: '/userDashboard', icon: FiHome },
  { label: '违法记录', path: '/userOffenseListPage', icon: FiAlertTriangle },
  { label: '车辆管理', path: '/vehicleManagement', icon: FiTruck },
  { label: '罚款信息', path: '/fineInformation', icon: FiCreditCard },
  { label: '业务进度', path: '/businessProgress', icon: FiLayers },
  { label: '在线办理进度', path: '/onlineProcessingProgress', icon: FiClipboard },
  { label: '我的申诉', path: '/userAppeal', icon: FiFileText },
  { label: '个人中心', path: '/personalMain', icon: FiUsers },
  { label: '个人设置', path: '/userSetting', icon: FiSettings },
  { label: '咨询反馈', path: '/consultation', icon: FiMessageCircle },
  { label: '新闻资讯', path: '/latestTrafficViolationNewsPage', icon: FiBookOpen },
];

export const utilityNav = [
  { label: '事故快处指南', path: '/accidentQuickGuidePage', icon: FiBookOpen },
  { label: '事故处理流程', path: '/accidentProgressPage', icon: FiBookOpen },
  { label: '事故证据采集', path: '/accidentEvidencePage', icon: FiBookOpen },
  { label: '事故视频教程', path: '/accidentVideoQuickPage', icon: FiBookOpen },
  { label: '罚款缴纳说明', path: '/finePaymentNoticePage', icon: FiBookOpen },
  { label: '扫一扫', path: '/mainScan', icon: FiTool },
  { label: '安全退出', path: '/login', icon: FiLogOut, isLogout: true },
];

