export const API_PATHS = {
  AUTH_LOGIN: '/api/auth/login',
  AUTH_REGISTER: '/api/auth/register',
  AUTH_USERS: '/api/auth/users',
  AUTH_REFRESH: '/api/auth/refresh',
  AUTH_LOGOUT: '/api/auth/logout',
  DRIVERS: '/api/drivers',
  VEHICLES: '/api/vehicles',
  OFFENSES: '/api/offenses',
  DEDUCTIONS: '/api/deductions',
  FINES: '/api/fines',
  PAYMENTS: '/api/payments',
  OFFENSE_TYPES: '/api/offense-types',
  PROGRESS: '/api/progress',
  USERS: '/api/users',
  ROLES: '/api/roles',
  PERMISSIONS: '/api/permissions',
  SYSTEM_LOGS: '/api/system/logs',
  SYSTEM_SETTINGS: '/api/system/settings',
  SYSTEM_BACKUP: '/api/system/backup',
  LOGIN_LOGS: '/api/logs/login',
  OPERATION_LOGS: '/api/logs/operation',
  SYSTEM_LOGS_OVERVIEW: '/api/system/logs/overview',
  LOGIN_LOGS_RECENT: '/api/system/logs/login/recent',
  OPERATION_LOGS_RECENT: '/api/system/logs/operation/recent',
  APPEAL_LIST: '/api/appeals',
  APPEAL_WORKFLOW_EVENT: (appealId: string | number, event: string) =>
    `/api/workflow/appeals/${appealId}/events/${event}`,
  AI_CHAT_STREAM: '/api/ai/chat',
  FEEDBACK: '/api/feedback',
  FEEDBACK_BY_ID: (id: string | number) => `/api/feedback/${id}`,
  AUTH_ME: '/api/auth/me',
  USERS_PASSWORD: '/api/users/me/password',
} as const;
