CREATE TABLE IF NOT EXISTS offense_type_dict (
  type_id INT AUTO_INCREMENT PRIMARY KEY,
  offense_code VARCHAR(64),
  offense_name VARCHAR(200),
  category VARCHAR(100),
  description TEXT,
  standard_fine_amount DECIMAL(10,2),
  min_fine_amount DECIMAL(10,2),
  max_fine_amount DECIMAL(10,2),
  deducted_points INT,
  detention_days INT,
  license_suspension_days INT,
  severity_level VARCHAR(50),
  legal_basis TEXT,
  status VARCHAR(50),
  created_at DATETIME NULL,
  updated_at DATETIME NULL,
  deleted_at DATETIME NULL,
  remarks TEXT
);

CREATE TABLE IF NOT EXISTS appeal_record (
  appeal_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  offense_id BIGINT,
  driver_id BIGINT,
  appeal_number VARCHAR(100),
  appellant_name VARCHAR(100),
  appellant_id_card VARCHAR(100),
  appellant_id_card_ciphertext TEXT,
  appellant_id_card_blind_index VARCHAR(255),
  appellant_contact VARCHAR(100),
  appellant_contact_ciphertext TEXT,
  appellant_contact_blind_index VARCHAR(255),
  appellant_email VARCHAR(255),
  appellant_address VARCHAR(255),
  appeal_type VARCHAR(100),
  appeal_reason TEXT,
  appeal_time DATETIME NULL,
  evidence_description TEXT,
  evidence_urls TEXT,
  acceptance_status VARCHAR(100),
  acceptance_time DATETIME NULL,
  acceptance_handler VARCHAR(100),
  rejection_reason TEXT,
  process_status VARCHAR(100),
  process_time DATETIME NULL,
  process_result TEXT,
  process_handler VARCHAR(100),
  created_at DATETIME NULL,
  updated_at DATETIME NULL,
  created_by VARCHAR(100),
  updated_by VARCHAR(100),
  deleted_at DATETIME NULL,
  remarks TEXT
);

INSERT INTO offense_type_dict (
  offense_code,
  offense_name,
  category,
  description,
  standard_fine_amount,
  deducted_points,
  severity_level,
  legal_basis,
  status,
  created_at,
  updated_at,
  remarks
) VALUES (
  'A001',
  'Illegal parking',
  'Parking',
  'Vehicle stopped in a restricted area.',
  200.00,
  3,
  'Minor',
  'Road Traffic Safety Law Article 93',
  'Active',
  NOW(),
  NOW(),
  'Seed row for Go RAG live integration.'
) ON DUPLICATE KEY UPDATE updated_at = VALUES(updated_at);

INSERT INTO appeal_record (
  offense_id,
  appeal_number,
  appellant_name,
  appeal_type,
  appeal_reason,
  appeal_time,
  evidence_description,
  acceptance_status,
  process_status,
  created_at,
  updated_at,
  remarks
) VALUES (
  1,
  'AP-2026-0001',
  'Alice',
  'Judgment_Error',
  'Evidence does not match the vehicle.',
  NOW(),
  'Camera frame mismatch.',
  'Accepted',
  'Under_Review',
  NOW(),
  NOW(),
  'Seed row for Go RAG live integration.'
) ON DUPLICATE KEY UPDATE updated_at = VALUES(updated_at);
